version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: auth0-lock
    versions:
    - 11.28.0
    - 11.28.1
    - 11.29.0
    - 11.29.1
  - dependency-name: typedoc
    versions:
    - 0.16.11
    - 0.20.28
    - 0.20.29
    - 0.20.30
    - 0.20.32
    - 0.20.33
    - 0.20.34
    - 0.20.35
  - dependency-name: three
    versions:
    - 0.126.0
    - 0.126.1
    - 0.127.0
  - dependency-name: "@types/uglify-js"
    versions:
    - 3.11.1
    - 3.12.0
  - dependency-name: "@types/auth0-lock"
    versions:
    - 11.27.0
  - dependency-name: "@types/selenium-webdriver"
    versions:
    - 4.0.11
  - dependency-name: ts-node
    versions:
    - 8.5.4
  - dependency-name: angular-router-loader
    versions:
    - 0.7.0
  - dependency-name: awesome-typescript-loader
    versions:
    - 4.0.1
  - dependency-name: exports-loader
    versions:
    - 0.7.0
  - dependency-name: karma-webpack
    versions:
    - 3.0.5
